# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CodingAssesment' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CodingAssesment

	pod 'AFNetworking', '~> 2.0'
	pod 'MBProgressHUD', '~> 1.0'

  target 'CodingAssesmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
